### ISSUE TITLE
Dos2unix

### ISSUE THREAD

**Issue by LeeGardiner** [san-kumar/installer#4]
I'm finding issues deploying on unix/linux from the latest composer which would suggest its been edited using a windows format and not cleaned prior to commit.

find . -type f -exec dos2unix {} \;

This is resulting in a broken deploy function on unix/linux os, once again, attempted to PR this but unfortunately I do not have the appropriate rights.

**Comment by san-kumar** [comment]
Thanks. I've done this to all files in latest version!
