### ISSUE TITLE
Please enable the php zip extension

### ISSUE THREAD

**Issue by fullergalway** [san-kumar/installer#5]
Thanks for this.

Any chance you could add the zip extension ```--enable-zip``` in the php configure options?

Note I tried building my own php using the upstream dockerfile, however my compiled version seems to be missing some options.

(Any chance you could include the dockerfile and the build wrapper.zip script?)

Thanks again.

**Comment by san-kumar** [comment]
It is enabled. Also enabled the following;

'--with-openssl' '--with-curl' '--with-zlib' '--with-jpeg-dir' '--with-freetype-dir' '--enable-mbstring' '--enable-zip' '--with-mcrypt' '--with-png-dir' '--with-pdo-mysql' '--with-gd'

Also added support for ImageMagick
